### ISSUE TITLE
filter projection applied twice not working

### ISSUE THREAD

**Issue by haikyuu** [jmespath/jmespath.js#10]
Hi, good job with this library :+1:  
Here is the filter `machines[?name=='a'].state[?a=='0']`

and the JSON 
```JSON
{
  "machines": [
    {"name": "a", "state":   [{"a":"running"}, {"a": "0"}]},
    {"name": "b", "state": "stopped"},
    {"name": "b", "state": "running"}
  ]
}
```
But it does not return anything ! Am i doing something wrong?

**Comment by jamesls** [comment]
Quick question, what would like the output to be?  Are you trying to search for any entry in the `machines` list where the name equals `a` *and* where the `state` key contains an element that has an `a` key that's equal to `0`?   In which case you want the output to be:

```
[{"name": "a", "state":   [{"a":"running"}, {"a": "0"}]}]
```

Is that correct?

**Comment by haikyuu** [comment]
Yes. After reading a little bit ^^' i found out i  had to **use pipes**. But 
 - this works `machines[?name=='a'] | [0].state[?a=='0']`
 - even though i expect this to work!  `machines[?name=='a'] | state[?a=='0']`
Thanks for the quick reply :)

**Comment by jamesls** [comment]
Just wanted to close the loop on this.  jep-9 is now implemented in jmespath.js, which adds native support for `and` expressions.  This make this type of query much more straightforward:

```
machines[?name=='a' && state[?a == `0`]]
```

I'm going to go ahead and close this issue out.  Let me know if you have any other questions.
