### ISSUE TITLE
Escaped values.

### ISSUE THREAD

**Issue by DylanPiercey** [jmespath/jmespath.js#11]
Is there a way to escape user provided keys for use in queries?

**Comment by jamesls** [comment]
Yes, you'll have to provide the value in double quotes.  For example, if a key had a double quote in it, you could use: `foo."key with space".bar`.

More examples:

`"key with space".bar.baz[0]`
`"key\nnewline" | [0].bar`

**Comment by DylanPiercey** [comment]
@jamesls So all I have to escape is double quotes?

**Comment by jamesls** [comment]
@DylanPiercey yep, exactly.
