### ISSUE TITLE
Feature Request: MongoDB support.

### ISSUE THREAD

**Issue by DylanPiercey** [jmespath/jmespath.js#12]
I think jmespath looks like an awesome alternative for the native query language for MongoDB and was wondering about implementing jmespath inside MongoDB (either overriding the existing query, or adding a script) that would allow for jmespath to work on the db level.

Has any one considered this? I'm not 100% sure its possible but it seems so.

This would likely be in another repository (not jmespath.js) but I'd like to start the conversation here.

**Comment by jamesls** [comment]
Sorry for the delay in responding.

I think this is a really interesting idea.  I have to admit, while I'm familiar with mongodb, I don't know that much about it and I'm not sure exactly what would be needed to implement jmespath inside MongoDB.

I'll mark this as "others-chime-in".  If anyone has any thoughts on this, please feel free to share.

**Comment by jamesls** [comment]
Closing out issue.  Again, if anyone has any thoughts, please feel free to share.

**Comment by xogeny** [comment]
I wonder if it would be possible to translate `jmespath` queries to/from MongoDB queries?  I haven't looked in detail at this but it would be pretty neat if it could be determined that they are isomorphic (or at least some subset of them was isomorphic) and formally define the mapping.

**Comment by JeffCarpenter** [comment]
I think the first step here would be adding BSON import and export plugins.
