### ISSUE TITLE
select jsonld @id

### ISSUE THREAD

**Issue by edsilv** [jmespath/jmespath.js#4]
Hi,

I'm running this query in your "try it out" tool:

    sequences[*].canvases[*].@id

for this jsonld:

http://wellcomelibrary.org/iiif/b18035723/manifest

which returns:

    [
      []
    ]

If I try:

    sequences[*].canvases[*].label

it returns the labels for every canvas.

Is there a way to get jmespath to recognise the "@id " property?

**Comment by jamesls** [comment]
Because the `@` character is used in JMESPath, you'll need to use double quotes around the field name:  `sequences[*].canvases[*]."@id"`.

**Comment by jamesls** [comment]
Closing out old issue.
