### ISSUE TITLE
Special characters in keys not working

### ISSUE THREAD

**Issue by laggingreflex** [jmespath/jmespath.js#53]
Special characters in keys don't work

If I have data like this:

```js
{ 'foo-bar': 'baz' }
```

And I use the search: `'foo-bar'`, it gives error.

```js
> jmespath.search({ 'foo-bar': 'baz' }, 'foo-bar')
Thrown:
{ ParserError: Unexpected token type: Number, value: NaN
    at Parser.parse (…\node_modules\jmespath\jmespath.js:502:27)
    at Object.search (…\node_modules\jmespath\jmespath.js:1660:25) name: 'ParserError' }
```

Lots of other special characters don't seem to work either: `.,/\|{}`

Tested on v0.15.0

**Comment by glenveegee** [comment]
Also `$` as in

`{"$foo": "bar"}`

**Comment by jdthorpe** [comment]
This version of jmespath doesn't have that particular problem: ` yarn add jmespath@0.14.0`

**Comment by glenveegee** [comment]
Actually it turns out that the spec dictates that when special characters in keys occur the key should be quoted

So in the example above...

**Comment by laggingreflex** [comment]
> Actually it turns out that the spec dictates that when special characters in keys occur the key should be quoted
> <pre>jmespath.search({ 'foo-bar': 'baz' }, '"foo-bar"')</pre>

Ahh! That's superb. It works. Thanks! 👍
