### ISSUE TITLE
Typecasting null value to be accepted inside join

### ISSUE THREAD

**Issue by rahul-gharat** [jmespath/jmespath.js#66]
Hi, I am processing a json which have array of object inside array of object with possibility of not having required key (or maybe null). and i want to perform join operation on result.

Data I have is as follows
`[{"id":3455,"items":[{"id":44099},{"id":6548},{"id":""},{"id":null},{}]},{"id":765765,"items":[]},{"id":2364576,"items":null},{"id":873254}]`

Expected Result
`[{"id":3455,"itemsid":"44099, 6548"},{"id":765765,"itemsid":""},{"id":2364576,"itemsid":""},{"id":873254,"itemsid":""}]`

The query I tried works for positive case but failes in case where expected value not exist.
`[].{"id":id,"itemsid": items[].to_string(id) | join(', ', @)}`

can someone please help here?

Thanks in advance.

**Comment by darrenmothersele** [comment]
The trick is to use OR to convert your null values to empty arrays, like this 
```
(items[].id || `[]`)
```

You can see your example full working here in this codesandbox:
https://codesandbox.io/s/cranky-bouman-8s7hc?file=/src/index.js

**Comment by rahul-gharat** [comment]
Thanks @darrenmothersele ,

I tried to use OR earlier, but I missed to add quote on brackets. Your solution is brilliant, it also has some additional checks.
