### ISSUE TITLE
Filter by numeric property throws error

### ISSUE THREAD

**Issue by Clonkex** [jmespath/jmespath.js#72]
Using this data as a test:

```
[
    {
        "id": 3,
        "otherData": "yo wassup"
    },
    {
        "id": 42,
        "otherData": "et cetera"
    }
]
```

I'm unable to filter a projection by `id` because `'[?id==42]'` gives me `Uncaught ParserError: Invalid token (Number): "42"`. Is there a workaround?

**Comment by darrenmothersele** [comment]
Try quoting the number as a literal, like this: 

    [?id==`42`]

CodeSandbox working example: https://codesandbox.io/s/fancy-morning-feznn?file=/src/index.js

**Comment by Clonkex** [comment]
@darrenmothersele Ta, I actually figured that out a little while later but forgot to close the issue.
