### ISSUE TITLE
Difference between specification and js implementation

### ISSUE THREAD

**Issue by IsoLinearCHiP** [jmespath/jmespath.js#9]
As per the grammar definiton and the example in http://jmespath.org/specification.html#id10 we supposedly can use at least `or-expressions` in filters ( called `bracket-specifier` in the grammar )

Additionally the `and-expression` does not seem to be allowed in the grammar even though the same example uses it ( and it would seem logical )

As far as I can tell the js implementation as of now does not support this, however I did not find any mention of it, and as such spent quite some time thinking I was getting the syntax wrong in my querys.

This is an example session I ran in the chrome console:
```
jmespath.search({"foo": [{"a": 1, "b": 2}, {"a": 1, "b": 3}]}, "foo[?a==`1`]")
[Object, Object]

jmespath.search({"foo": [{"a": 1, "b": 2}, {"a": 1, "b": 3}]}, "foo[?b==`2`]")
[Object]

jmespath.search({"foo": [{"a": 1, "b": 2}, {"a": 1, "b": 3}]}, "foo[?a==`1`||b==`2`]")
[]
```

Logically the expected result for me should either be both objects or an exception informing me about a syntax error, like when I try using the documented but utterly unimplemented `and-expression`

```
jmespath.search({"foo": [{"a": 1, "b": 2}, {"a": 1, "b": 3}]}, "foo[?a==`1`&&b==`2`]")
jmespath.js:497 Uncaught Error {name: "ParserError", stack: (...), message: "Expected Rbracket, got: Expref"}
```

**Comment by jamesls** [comment]
jmespath.js does not support the newly added `and-expressions` and the generalized expression in a filter.  I'll get this updated soon.
